# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AzSsh < Formula
  desc "A fast, beautiful TUI for managing Azure VMs and SSH connections."
  homepage "https://github.com/shyamnborole/azure-ssh-tui"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shyamnborole/azure-ssh-tui/releases/download/v1.0.0/azure-ssh-tui_Darwin_x86_64.tar.gz"
      sha256 "84fa539572bb1d36de0d621c55e3d577bedaf81b20811a5157bef4324efeaf0a"

      define_method(:install) do
        bin.install "az-ssh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shyamnborole/azure-ssh-tui/releases/download/v1.0.0/azure-ssh-tui_Darwin_arm64.tar.gz"
      sha256 "de6badab1245428a8d61ec456a03d588a731b2e6f7e465dddb6220b7718199ad"

      define_method(:install) do
        bin.install "az-ssh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shyamnborole/azure-ssh-tui/releases/download/v1.0.0/azure-ssh-tui_Linux_x86_64.tar.gz"
      sha256 "9b95a75033b4644e2684a523339ed3d01ef373df3aac68698ac63c27fb57106c"
      define_method(:install) do
        bin.install "az-ssh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shyamnborole/azure-ssh-tui/releases/download/v1.0.0/azure-ssh-tui_Linux_arm64.tar.gz"
      sha256 "bba7e8dca1f8a856547911838cc67577b914577d2c49aa2c23c0e14b8061cdac"
      define_method(:install) do
        bin.install "az-ssh"
      end
    end
  end

  def caveats
    <<~EOS
      ⚠️ This application requires the Azure CLI (az) to be installed and authenticated.
      If you don't have it, run: brew install azure-cli
    EOS
  end

  test do
    system "#{bin}/az-ssh --version"
  end
end
