# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AzSsh < Formula
  desc "A fast, beautiful TUI for managing Azure VMs and SSH connections."
  homepage "https://github.com/shyamnborole/azure-ssh-tui"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shyamnborole/azure-ssh-tui/releases/download/v1.0.0/azure-ssh-tui_Darwin_x86_64.tar.gz"
      sha256 "9146d81cfc860e73355ff307a2686b3c3410c4342f7d3bd055b2e18b3e0c9ed3"

      define_method(:install) do
        bin.install "az-ssh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shyamnborole/azure-ssh-tui/releases/download/v1.0.0/azure-ssh-tui_Darwin_arm64.tar.gz"
      sha256 "53be6e6c1e6db3285924a87966ed215652a5e27ba46a11d07087364578d37ff0"

      define_method(:install) do
        bin.install "az-ssh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shyamnborole/azure-ssh-tui/releases/download/v1.0.0/azure-ssh-tui_Linux_x86_64.tar.gz"
      sha256 "5921324ae666c44594ac5e6590546a3efa6659433f844151b07fd858e289c197"
      define_method(:install) do
        bin.install "az-ssh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shyamnborole/azure-ssh-tui/releases/download/v1.0.0/azure-ssh-tui_Linux_arm64.tar.gz"
      sha256 "4d54c9d27d5002f796adcc23b4eaffc51dba7d34617fa0aa72a8bcb3f53f2fe4"
      define_method(:install) do
        bin.install "az-ssh"
      end
    end
  end

  def caveats
    <<~EOS
      ⚠️ This application requires the Azure CLI (az) to be installed and authenticated.
      If you don't have it, run: brew install azure-cli
    EOS
  end

  test do
    system "#{bin}/az-ssh --version"
  end
end
