# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AzSsh < Formula
  desc "A fast, beautiful TUI for managing Azure VMs and SSH connections."
  homepage "https://github.com/shyamnborole/azure-ssh-tui"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shyamnborole/azure-ssh-tui/releases/download/v1.0.1/azure-ssh-tui_Darwin_x86_64.tar.gz"
      sha256 "b1827ea7d1504f67cb8a87d95218e541827ecedbb5267cc1e27748bffff76273"

      define_method(:install) do
        bin.install "az-ssh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shyamnborole/azure-ssh-tui/releases/download/v1.0.1/azure-ssh-tui_Darwin_arm64.tar.gz"
      sha256 "658d0c17f6895c861351919f8e36005c90b3bc6685b6842527800ba7a71e2cfa"

      define_method(:install) do
        bin.install "az-ssh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shyamnborole/azure-ssh-tui/releases/download/v1.0.1/azure-ssh-tui_Linux_x86_64.tar.gz"
      sha256 "8685d7fc6469b32a7e5b5886e0e9e2df17b03a1b2dbcd07e03e5fad69077cbaf"
      define_method(:install) do
        bin.install "az-ssh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shyamnborole/azure-ssh-tui/releases/download/v1.0.1/azure-ssh-tui_Linux_arm64.tar.gz"
      sha256 "fc783ec589a1650834e4bbcdcb7f8f1115985f9b12b4c65f033af0bd91822442"
      define_method(:install) do
        bin.install "az-ssh"
      end
    end
  end

  def caveats
    <<~EOS
      ⚠️ This application requires the Azure CLI (az) to be installed and authenticated.
      If you don't have it, run: brew install azure-cli
    EOS
  end

  test do
    system "#{bin}/az-ssh --version"
  end
end
